# Generated by Django 3.2.8 on 2022-06-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='user',
        ),
    ]
